# if else and elif statements are a multiway decision 
# taken by our program due to certain condition
# in our code.



#syntax:
'''
a = int(input(" enter your age "))

if (a>=18):
    print(" you are adult: ")
    print(' you are able to anything: ')
                                        
    
    
else: 
    print(" you are below 18, not able: ")
    
    '''
    
    
# Code Example.
'''
a=22
if(a>9):
    print("greater")
else:
    print("lesser")
    '''
    
    # quick Quiz:  Write a program to print yes when the age entered by
    # the user is greater than or equal to 18 
    
    
age = int(input(" enter your age "))
if (age>17):
    print(' you are adult ')
    
else:
    print(' you are teen')